version: '3.8'
services:
  web:
    container_name: web_container
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    command: >
      sh -c "
              python manage.py makemigrations --noinput &&
              python manage.py migrate --noinput &&
              python manage.py collectstatic --noinput &&
              python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    container_name: db_container
    restart: always
    image: postgres
    volumes:
      - .dbdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "54321:5432"

